# Generated by Django 4.1.1 on 2022-10-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('deadline', models.DateField(null=True)),
                ('email', models.EmailField(default='nkawaako@gmail.com', max_length=254, null=True)),
            ],
        ),
    ]
